{% set version = "0.3.3" %}

package:
  name: sat-stac
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sat-stac/sat-stac-{{ version }}.tar.gz
  sha256: 5008d129fea7e5fe528009b9b1b045da201664c48f6bdd6cc1e0560d4bcd5b55

build:
  number: 0
  noarch: python
  entry_points:
    - sat-stac=satstac.cli:cli
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-dateutil >=2.7.5,<2.8
    - requests >=2.19.1

test:
  imports:
    - satstac
  commands:
    - sat-stac --help

about:
  home: https://github.com/sat-utils/sat-stac.git
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A Python library for working with Spatio-Temporal Asset Catalogs (STAC)"

extra:
  recipe-maintainers:
    - ocefpaf
